# Generated by Django 6.0.5 on 2026-05-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('coverage_percent', models.PositiveIntegerField(default=0, help_text='Default % covered')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=80)),
                ('coverage_percent', models.PositiveIntegerField(default=0, help_text='Override; 0 = use provider default')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='patients.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insuranceprovider')),
            ],
        ),
    ]
